version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: xi_postgres
    environment:
      POSTGRES_USER: xi_user
      POSTGRES_PASSWORD: xi_pass
      POSTGRES_DB: xi_db
    volumes:
      - xi_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api/MyFootballXI.API
      dockerfile: Dockerfile
    container_name: xi_api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=xi_db;Username=xi_user;Password=xi_pass

volumes:
  xi_db_data:
